CONFIG = 'bottleneck'
MODULE = 'ppgs'

REPRESENTATION = 'bottleneck'
INPUT_CHANNELS = 144
NUM_WORKERS=6
MODEL = 'transformer'
EVALUATION_BATCHES = 16

NUM_HIDDEN_LAYERS = 5
MAX_FRAMES = 100000
HIDDEN_CHANNELS = 512